### ISSUE TITLE
Exception in add route through fboss_route.py 

### ISSUE THREAD

**Issue by andrianyablonskyy** [facebook/fboss#1]
There is an error during add route through the fboss script.
#=================================================
Traceback (most recent call last):
  File "fboss_route.py", line 18, in <module>
    from neteng.fboss.ctrl import FbossCtrl
ImportError: No module named neteng.fboss.ctrl
#=================================================

Steps to reproduce:
1. Start wedge_agent from sudo (# ./wedge_agent --config sample1.json)
2. Change directory to './fboss/agent/tools'
3. Start fboss_route.py (# python fboss_route.py add prefix=1.1.1.0/24 nexthop=10.1.1.1)

**Comment by oridb** [comment]
It looks like there are three problems, and two of them are our bugs:

- First, we're not generating the Python bindings for the Thrift interface.
- Second, the import path for the thrift interface is wrong.

Finally, running the Python scripts will need to modify the PYTHONPATH to include the generated
thrift bindings.

I'll look at getting that fixed soon.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
