### ISSUE TITLE
Build failed on ubuntu 14.04 with thrift/lib/cpp/async/TEventBase.h: No such file or directory

### ISSUE THREAD

**Issue by smbay** [facebook/fboss#21]
[ 16%] Building CXX object CMakeFiles/fboss_agent.dir/fboss/agent/Main.cpp.o
[ 17%] Building CXX object CMakeFiles/fboss_agent.dir/fboss/agent/NeighborListenerClient.cpp.o
/home/osboxes/git/fboss/fboss/agent/NeighborListenerClient.cpp:12:45: fatal error: thrift/lib/cpp/async/TEventBase.h: No such file or directory
 #include <thrift/lib/cpp/async/TEventBase.h>
                                             ^
compilation terminated.
make[2]: *** [CMakeFiles/fboss_agent.dir/fboss/agent/NeighborListenerClient.cpp.o] Error 1
make[1]: *** [CMakeFiles/fboss_agent.dir/all] Error 2
make: *** [all] Error 2

**Comment by oridb** [comment]
You need to replace that with folly::EventBase.

I have a version with that change on my personal github (https://github.com/oridb/fboss), and will be pushing an official release with that change live in the next day or so.

**Comment by smbay** [comment]
Thanks . (https://github.com/oridb/fboss), is compiling fine .  But now there is a  a linker error
/usr/bin/ld: /usr/local/lib/libfolly.so: undefined reference to symbol 'deflate'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [wedge_agent] Error 1
make[1]: *** [CMakeFiles/wedge_agent.dir/all] Error 2
make: *** [all] Error 2

**Comment by oridb** [comment]
Keep an eye on things here -- we're pushing a bunch of fixes.

**Comment by oridb** [comment]
This should be fixed.
