### ISSUE TITLE
 fboss_route.py error

### ISSUE THREAD

**Issue by smbay** [facebook/fboss#34]
I am getting the following error when i followed the instructions in Readme.md
osboxes@osboxes:~/git/fboss/fboss/agent/tools$ python fboss_route.py host add 172.31.0.0/24 172.16.1.1
Traceback (most recent call last):
  File "fboss_route.py", line 19, in <module>
    from neteng.fboss.ctrl import FbossCtrl
  File "/home/osboxes/git/fboss/buiild/gen/fboss/agent/if/gen-py/neteng/fboss/ctrl/FbossCtrl.py", line 10, in <module>
    from thrift.util.Recursive import fix_spec
ImportError: No module named util.Recursive

**Comment by oridb** [comment]
You may need to adjust your python path. It looks like Thrift provides that package, so I'd look in external/fbthrift/ for the file.

**Comment by smbay** [comment]
Thanks . it helped.
