### ISSUE TITLE
./getdeps.sh fails during building of thrift on the latest code on Ubuntu 14.04

### ISSUE THREAD

**Issue by vitaliy-senchyshyn** [facebook/fboss#37]
I see a compilation error as follows when try to execute ./getdeps.sh on the latest fboss sources:

/bin/sh ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I../../..  -pthread -I/usr/include  -I../cpp -I../../../../gperftools-2.0.99/src -I/home/vsenchyshyn/projects/xpliant/tmp/fboss/external/folly -I/home/vsenchyshyn/projects/xpliant/tmp/fboss/external/wangle  -std=gnu++0x -MT libthriftcpp2_la-GeneratedCodeHelper.lo -MD -MP -MF .deps/libthriftcpp2_la-GeneratedCodeHelper.Tpo -c -o libthriftcpp2_la-GeneratedCodeHelper.lo `test -f 'GeneratedCodeHelper.cpp' || echo './'`GeneratedCodeHelper.cpp
make[5]: *** No rule to make target 'asybc/SaslNegotiationHandler.cpp', needed by 'asybc/libthriftcpp2_la-SaslNegotiationHandler.lo'.  Stop.
make[5]: *** Waiting for unfinished jobs....

**Comment by oridb** [comment]
I can look into this, but this is not an fboss issue -- If you can file an issue with thrift, that would probably be more helpful.

**Comment by vitaliy-senchyshyn** [comment]
Well, previous versions of getdeps.sh contained exact versions of the external libraries needed. Here the same could serve as a fix as well.

**Comment by vitaliy-senchyshyn** [comment]
Compilation works with the following versions of folly and fbthrift specified in getdeps.sh:

update https://github.com/facebook/folly.git 08dba5714790020d2fa677e34e624eb4f34a20ca
update https://github.com/facebook/fbthrift.git 1b2b03a472c41915a8c481a06edc630674377e77

**Comment by oridb** [comment]
FYI, we should require Xenial for future builds -- in any case, closing this, since it worked for you.
