### ISSUE TITLE
Issues in build

### ISSUE THREAD

**Issue by rain-man-** [facebook/fboss#4]
I am facing a problem while building. I used the getdeps.sh for the dependencies and followed rest of the build instructions, but make command errored out with the below messages. Anybody have any suggestions? 

--------------------------------------------------------------------------------------------------------------------------
~/home/workspace/fboss/fboss/agent/ThriftHandler.cpp: In lambda function:
~/home/workspace/fboss/fboss/agent/ThriftHandler.cpp:391:21: error: ‘class facebook::stats::ExportedStatMap’ has no member named ‘getStatPtr’
     return statMap->getStatPtr(statName)->getSum(0);
                     ^
~/home/workspace/fboss/fboss/agent/ThriftHandler.cpp: In lambda function:
~/home/workspace/fboss/fboss/agent/ThriftHandler.cpp:395:15: error: void value not ignored as it ought to be ctr.bytes = getSumStat(prefix, "bytes");
               ^
~/home/workspace/fboss/fboss/agent/ThriftHandler.cpp:396:19: error: void value not ignored as it ought to be ctr.ucastPkts = getSumStat(prefix, "unicast_pkts");
                   ^
~/home/workspace/fboss/fboss/agent/ThriftHandler.cpp:397:23: error: void value not ignored as it ought to be ctr.multicastPkts = getSumStat(prefix, "multicast_pkts");
                       ^
~/home/workspace/fboss/fboss/agent/ThriftHandler.cpp:398:23: error: void value not ignored as it ought to be ctr.broadcastPkts = getSumStat(prefix, "broadcast_pkts");
                       ^
~/home/workspace/fboss/fboss/agent/ThriftHandler.cpp:399:23: error: void value not ignored as it ought to be ctr.errors.errors = getSumStat(prefix, "errors");
                       ^
~/home/workspace/fboss/fboss/agent/ThriftHandler.cpp:400:25: error: void value not ignored as it ought to be ctr.errors.discards = getSumStat(prefix, "discards");

**Comment by oridb** [comment]
Should be fixed in f4811de1700f9d8f2d028fc43dcafb9b0f78c913
