### ISSUE TITLE
fboss build fails with "folly/folly-config.h" no such file or directory..

### ISSUE THREAD

**Issue by nbellari** [facebook/fboss#45]
Hi,

I am trying build fboss on my box, installed all the necessary dependencies with "getdeps.sh", but the build fails with the above error - I could see that in the repository pulled by the script, such a file does not exist.

Can somebody tell me how to get past this issue?

Thanks,
-nagp

**Comment by oridb** [comment]
To be clear, it's folly that's failing to build when you run getdeps.sh?

Can you give me:

1. The os version that you are trying to build on
2. The command that you ran
3. The full output of the build including the error

Thanks.

**Comment by nbellari** [comment]
Hi,
Sorry for a late reply.
Here is the full output of "getdeps.sh": http://pastebin.com/SvKifqJa

I am compiling fboss on a ONL platform which is like this:
--
root@localhost:~/fboss# uname -a
Linux localhost 3.18.25-OpenNetworkLinux #1 SMP Thu Sep 1 18:34:44 UTC 2016 x86_64 GNU/Linux
root@localhost:~/fboss# 
--

Please let me know if I can give any other information.

**Comment by oridb** [comment]
building folly/folly...
    configure: error: cannot find install-sh, install.sh, or shtool in build-aux "."/build-aux

These come from automake/autoconf's setup scripts. Have you got them installed correctly? Can you manually try running the commands in getdeps.sh to build folly?

**Comment by oridb** [comment]
Any luck?

By the way, if you keep track of the packages that the package install command (`./getdeps.sh pkg`) is missing, can you either give me a pull request, or list them here so that I can add them?

**Comment by nbellari** [comment]
I have installed the fboss packages from the ONL repository as mentioned in this link (https://goo.gl/pM1cLH).

Thanks for your kind help!!

**Comment by nbellari** [comment]
Hi Ori,

The fboss package installation went successfully, but starting it is giving an error message as below. Can you please tell me if I am missing something?:

![fboss error](https://cloud.githubusercontent.com/assets/219543/19211821/59bbff44-8d63-11e6-98f5-6cc2a6f77ee5.jpg)

**Comment by oridb** [comment]
I don't believe that's a message printed by fboss. Try running the agent manually.

I suspect that's going to be an issue with the init scripts.

**Comment by sonoble** [comment]
You can edit the fboss_wedge_agent script in /etc/init.d and change it so that it checks for the wedge100.  

elif [ $PLATFORM != x86-64-facebook-wedge100-r0 ] ; then
    log_failure_msg "Failed: FBOSS not supported for platform $PLATFORM"
    exit 0

This will still probably fail due to the fact that OpenNSL we download is for the Wedge40 and there is no public release of OpenNSL 6.4.6.6 for the Wedge100.

We are currently working on FBOSS for the Wedge100 on ONL, but I don't have an ETA yet.

**Comment by sonoble** [comment]
FBOSS for Wedge 100 on ONL is now in beta 👍 

From a clean install of the latest debian 8 version of ONL : http://opennetlinux.org/binaries/latest-DEB8-AMD64-installed.installer

Run: dhclient ma1; apt-get update; apt-get install fboss-w100
answer yes to the unsigned packages
then you can run /etc/init.d/fboss_wedge_agent start

most of the fboss_route.py options work, except for list_ports and list_optics (I need time to debug this).

The sample config has all of the ports broken into 4x25G, so you will need to do some work there depending on your setup.

**Comment by capveg** [comment]
Just added Travis support so we get better alerts when the build breaks.  I believe this has been fixed.  Can you please confirm?  Also, fyi: https://travis-ci.org/facebook/fboss

**Comment by capveg** [comment]
Closing this out - seems fixed.
