### ISSUE TITLE
Link failure

### ISSUE THREAD

**Issue by sandeshrk** [facebook/fboss#51]
I am unable to build fboss agent. I ran ./getdeps.sh before building fboss. No errors reported.
Can someone please advise on this?

Thanks,
Sandesh

[100%] Linking CXX executable wedge_agent
../external/fbthrift/thrift/lib/cpp2/.libs/libthriftcpp2.so: undefined reference to `vtable for apache::thrift::ThriftProcessor'
collect2: error: ld returned 1 exit status
CMakeFiles/wedge_agent.dir/build.make:263: recipe for target 'wedge_agent' failed
make[2]: *** [wedge_agent] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/wedge_agent.dir/all' failed
make[1]: *** [CMakeFiles/wedge_agent.dir/all] Error 2
Makefile:83: recipe for target 'all' failed

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
uname -a
Linux  4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by capveg** [comment]
Hi - thanks for the heads up.  Fwiw, we were tracking this in our travis-ci.org build (check out https://travis-ci.org/facebook/fboss) and the fix is in flight.  In fact, I've just now restarted the travis build and believe it should build successfully.  If you can confirm it works for you as well, it would be appreciated.  Thanks for the bug report.

FYI: @eduardo-elizondo

**Comment by sandeshrk** [comment]
Thanks Rob. I am already updated to the latest git.
Can you tell me which fix I need to look at? I can test it and let you know.

Regards,
Sandesh

**Comment by sandeshrk** [comment]
Now, ./getdeps.sh errors out with this error.
make[5]: *** No rule to make target 'server/transport/core/ThriftProcessor.cpp', needed by 'server/transport/core/libthriftcpp2_la-ThriftProcessor.lo'.  Stop.
make[5]: *** Waiting for unfinished jobs....

**Comment by capveg** [comment]
There are some issues with how we do continuous integration with the github.com/facebook/fbthrift project that we're resolving internally, but short story is we'll get this fixed today.  

Curious: what are you looking to use fboss for?

**Comment by sandeshrk** [comment]
Thanks Rob.
I am trying to get the data on some optics information from wedge-100.

Sandesh

**Comment by jonahw** [comment]
An email you sent to 'ktr-github@dea.spamcon.org' was refused by the remote mail server.

No additional information is available.
