### ISSUE TITLE
How to build the utilities found in fboss/fboss/util/

### ISSUE THREAD

**Issue by Lewis-Kang** [facebook/fboss#58]
Hi,

I follow the steps described in **BUILD.md,** the following three executable files can be generated in _build/_ folder:
**wedge_agent, 
qsfp_service, 
agent_test**

But there is no **sim_agent** as mentioned in **BUILD.md.**

There are utility codes  in _fboss/fboss/util/_. Is there a document describing how to build those utilities?

Thanks in advance.

Lewis

**Comment by capveg** [comment]
Hi Lewis,

I'll take a look at trying to get those utilities compiled - a bunch of them are only useful for debugging very niche things.  Was there a specific utility you were interested in?  Also, regarding sim_agent - did you want to use it or were you just (completely reasonably) confused that it was mentioned in the documentation but not built?

Bottom line is that these utilities don't really get used so no time has been put into making them work in open source.  If you have a specific priority or interest in one of the tools, I can prioritize making that work.  Just let me know.

**Comment by Lewis-Kang** [comment]
Hi Rob,

Thanks for your quick response.
The utility we need is cp2112_util.
Yes. I am confused that the documentation says sim_agent will be generated after the build,, but I can't find it. Also, is there a guideline on running sim_agent? It would be great if we can try run FBOSS on a virtual switch.

Thanks for your help again.

Lewis

**Comment by capveg** [comment]
With https://github.com/facebook/fboss/commit/ecdaa7fb6bd4b36d4a73a29c2229b27e29fac5eb
I've added the magic to the build system to build cp2112_util and wedge_qsfp_util.  Neither are terribly user friendly - let me know if you need help getting them to work.

**Comment by Lewis-Kang** [comment]
Thanks Rob.
