### ISSUE TITLE
Cannot run system_tests

### ISSUE THREAD

**Issue by Blyschak** [facebook/fboss#66]
Hi.

After I updated local repo, I cannot run system_tests. Cannot find  fboss.system_tests.facebook package required here: [https://github.com/facebook/fboss/blob/master/fboss/system_tests/testutils/test_topology.py#L10](url)

`~/fboss/fboss/system_tests# python3 system_tests.py --config test_topologies/example_topology.py --test_dirs tests/`
`Traceback (most recent call last):`
`  File "system_tests.py", line 229, in <module>`
`    sys.exit(main(sys.argv))`
`  File "system_tests.py", line 225, in main`
`    run_tests(options)`
`  File "system_tests.py", line 190, in run_tests`
`    options.test_topology = dynamic_generate_test_topology(options)`
`  File "system_tests.py", line 94, in dynamic_generate_test_topology`
`    spec.loader.exec_module(module)`
`  File "<frozen importlib._bootstrap_external>", line 673, in exec_module`
`  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed`
`  File "test_topologies/example_topology.py", line 6, in <module>`
`    from fboss.system_tests.testutils.test_topology import (TestHost,`
`  File "/usr/lib/python3/dist-packages/fboss/system_tests/testutils/test_topology.py", line 10, in <module>`
`    from fboss.system_tests.facebook.utils.agent_config import (`
`ImportError: No module named 'fboss.system_tests.facebook'`

According to TESTING.md fboss/system_tests/facebook directory is internal.

Same with libfb package here: [https://github.com/facebook/fboss/blob/master/fboss/system_tests/testutils/paramiko_utils.py#L8](url)

Thanks

**Comment by capveg** [comment]
Sorry - this is a bug.  I've got a fixed written up and it should be public before the end of the day.  Thanks for catching this.

**Comment by capveg** [comment]
This should be fixed so closing this out - please re-open if this is not the case.
